#
# Makefile for aura sync drivers.
#
obj-y		+= ene_8k41.o
#obj-y		+= ms51_side.o
#obj-y		+= sky81298.o
obj-m  		+= ml51fb9ae_inbox.o
obj-m  		+= ms51_inbox.o
obj-m    	+= ene_6k582_station.o
obj-m		+= ene_8k41_dock.o

# ASUS_SZ_BSP Yadong : Add for factory test +++
#ifeq ($(ASUS_FTM), y)
#obj-m	+= ene_8k41_inbox.o
#endif
# ASUS_SZ_BSP Yadong : Add for factory test ---

#obj-$(CONFIG_AURA_SYNC_INBOX)	+= ene_8k41_inbox.o
#obj-$(CONFIG_AURA_SYNC_STATION)	+= ene_8k41_station.o
#obj-$(CONFIG_AURA_SYNC_POGO)	+= ene_8k41_pogo.o
