# make sure that the environment variables ARCH and CROSS_COMPILE
# are set for your architecture and cross compiler
#
# e.g. for Beaglebone black:
# export ARCH := arm
# export CROSS_COMPILE := arm-linux-gnueabihf-
#
# e.g. Samsung Galaxy S6:
# export ARCH := arm64
# export CROSS_COMPILE := aarch64-linux-android-

# In case of out of tree build, build as a module
# (when build inside kernel we will not enter this directory and this will have no effect)

# We can build either as part of a standalone Kernel build or as
# an external module.  Determine which mechanism is being used
ifeq ($(MODNAME),)
	KERNEL_BUILD := 1
else
	KERNEL_BUILD := 0
endif

ifeq ($(KERNEL_BUILD), 1)
	# These are configurable via Kconfig for kernel-based builds
	# Need to explicitly configure for Android-based builds
	AUDIO_BLD_DIR := $(shell pwd)/kernel/msm-4.19
	AUDIO_ROOT := $(AUDIO_BLD_DIR)/techpack/audio
endif


ifeq ($(CONFIG_ARCH_KONA), y)
	include $(AUDIO_ROOT)/config/konaauto.conf
	INCS    +=  -include $(AUDIO_ROOT)/config/konaautoconf.h
endif


RT5683_OBJS += rt5683.o

obj-$(CONFIG_SND_SOC_RT5683) := snd-soc-rt5683.o
snd-soc-rt5683-y := $(RT5683_OBJS)
